
spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/fruit}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:example}
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

server.error.include-message: always

server:
  ssl:
    key-store-type: PKCS12
    keyStore: classpath:certs/server/server-keystore.pfx
    trustStore: classpath:certs/server/server-truststore.pfx
    keyStorePassword: example
    trustStorePassword: example
    clientAuth: NEED
logging:
  level:
    org.springframework.security: DEBUG